(function(){
  "use strict";

  const data = {
    'bronco-289': {
      title: '1968 Ford Bronco — 289 CID',
      category: 'Automotive',
      summary: 'Ground-up restomod blending vintage Bronco character with modern drivability and serviceable systems.',
      description: [
        'This 1968 Ford Bronco was transformed from a bare frame into a fully modernized classic — a ground-up rebuild that blends vintage character with 21st-century engineering. Every system was redesigned for performance, reliability, and refinement while preserving the unmistakable spirit of the original truck.',
        'Under the hood, the factory 289 V8 was retained but upgraded with Edelbrock\'s Pro-Flo 4 electronic fuel injection system for seamless cold starts, self-tuning fuel maps, and improved throttle response. A custom stainless-steel fuel system, high-flow in-tank pump, 10-micron filtration, and adjustable regulator keep the engine supplied with precise pressure under any load.',
        'The front accessory drive was re-engineered using a CVF Racing serpentine system with integrated A/C, power steering, and alternator — packaged around a compact short water pump for optimal clearance. Cooling is handled by a 2-core aluminum radiator paired with a 4000 CFM electric fan triggered by the ECU. The wiring architecture, battery isolator circuit, and relay network were designed from scratch to handle modern electrical loads with OEM-level reliability.',
        'From the hydroboost braking system to the dual-battery layout, every detail was built to function flawlessly and look intentional. The result is a Bronco that starts, drives, and performs like a modern vehicle — yet feels every bit as raw, mechanical, and iconic as it did in 1968.'
      ],
      gallery: [
        { src: 'images/placeholders/bb1.JPG', alt: 'Condenser Installation' },
        { src: 'images/placeholders/bb3.JPG', alt: 'Engine Bay Pre-Cooling System' },
        { src: 'images/placeholders/bb4.JPG', alt: 'Exterrior Post Body Mounting' },
        { src: 'images/placeholders/bb5.JPG', alt: 'Interior Pre-Upholstry' },
        { src: 'images/placeholders/bb6.JPG', alt: 'Interior Post Upholstry & Trim' },
        { src: 'images/placeholders/bb7.JPG', alt: 'Vehicle Badging' },
        { src: 'images/placeholders/bb8.JPG', alt: 'Initial Body Mockup Post Suspension Overhaul' },
        { src: 'images/placeholders/bb9.JPG', alt: 'Billet Front Drive System Adapted to Ford 289' },
        { src: 'images/placeholders/bb10.JPG', alt: 'Suspension Overhaul' },
        { src: 'images/placeholders/bb11.JPG', alt: 'Complete Build During Testing Procedure' },
        { src: 'images/placeholders/bb12.JPG', alt: 'Body Mounting Process' },
        { src: 'images/placeholders/bb13.JPG', alt: 'Interrior Insulation Process' },
        { src: 'images/placeholders/bb14.JPG', alt: 'Hydraulic Hood Struts' },
        { src: 'images/placeholders/bb15.JPG', alt: 'AC Plumbing Body Preparation' },
        { src: 'images/placeholders/bb16.JPG', alt: 'Disc Brake Conversion' },
        { src: 'images/placeholders/bb17.JPG', alt: 'Complete Build' },
        { src: 'images/placeholders/bb18.JPG', alt: 'Disc Brake Conversion Process - Spindle Adaptation' },
        { src: 'images/placeholders/bb19.JPG', alt: 'Complete Interrior' },
        { src: 'images/placeholders/bb20.JPG', alt: 'Complete Interrior Rear' },
        { src: 'images/placeholders/bb21.JPG', alt: 'Pre-modification Front Knuckle' },
        { src: 'images/placeholders/bb22.JPG', alt: 'Project Start Point' },
        { src: 'images/placeholders/bb23.JPG', alt: 'Interior Post Upholstry & Trim' },
        { src: 'images/placeholders/bb25.JPG', alt: 'Passenger Kick Panel AC Plumbing' },
        { src: 'images/placeholders/bb26.JPG', alt: 'Rear Carpetting Post Upholstry & Fitment' },
        { src: 'images/placeholders/bb27.JPG', alt: 'Dashboard Layout' },
        { src: 'images/placeholders/bb28.JPG', alt: 'Complete Build' },
        { src: 'images/placeholders/bb29.JPG', alt: 'Complete Build' },
        { src: 'images/placeholders/bb30.JPG', alt: 'Complete Build' },
        { src: 'images/placeholders/bb31.JPG', alt: 'Custom Front Door Card With Morel Hybrid Integra' },
        { src: 'images/placeholders/bb32.JPG', alt: 'Engine / Drivetrain Wiring Process' },
        { src: 'images/placeholders/bb33.JPG', alt: 'Pre-paint Body Alignment' },
        { src: 'images/placeholders/bb34.JPG', alt: 'Dual Exhaust Fabrication & Installation' },
        { src: 'images/placeholders/bb35.JPG', alt: 'Polished True Dual Headers' },
        { src: 'images/placeholders/bb36.JPG', alt: 'Pro Flo 4 EFI Installation' },
        { src: 'images/placeholders/bb37.JPG', alt: 'Post Paint Body Alignment' },
        { src: 'images/placeholders/bb38.JPG', alt: 'Complete Build Interior' },
        { src: 'images/placeholders/bb39.JPG', alt: 'Complete Build During Testing Procedure' },
        { src: 'images/placeholders/bb40.JPG', alt: 'Rolling Chassis Post Striping Paint' },
        { src: 'images/placeholders/bb41.JPG', alt: 'Engine Bay Pre Linkage & Interior Integration' },
        { src: 'images/placeholders/bb42.JPG', alt: 'Complete EFI Conversion' }
      ],
    },
    'bronco-coyote': {
      title: '1968 Ford Bronco — 5.0L Gen 4x Coyote',
      category: 'Automotive',
      summary: 'Modernized restomod featuring a late-model Coyote swap, new wiring, and instrumentation.',
      gallery: [
        { src: 'images/placeholders/bronco_coy_1.jpg', alt: 'Placeholder illustration highlighting the Coyote Bronco engine bay.' },
        { src: 'images/placeholders/more-images-coming-soon.svg', alt: 'Animated graphic stating that more Coyote Bronco images are coming soon.' }
      ],
    },
    'jeep-cj5': {
      title: '1974 Jeep CJ5 — 304 CID',
      category: 'Automotive',
      summary: 'Purpose-built CJ-5 rebuild focused on reliable V8 power, simplified electrics, and trail-ready serviceability.',
      description: [
        'This Jeep CJ-5 build began as a raw, character-filled classic and was transformed into a purpose-built off-road machine that preserves the simplicity of the original while elevating its reliability and performance. Every mechanical system was re-engineered, refined, and tuned by hand to create a rig that\'s as tough as it is responsive.',
        'Power comes from an AMC 304 V8 fitted with a high-output HEI ignition, long-tube headers, and Cherry Bomb exhausts that give it a deep, unmistakable tone. The entire ignition and fuel system were redesigned for consistency and easy serviceability — replacing the outdated points ignition with a modern, high-voltage system gapped and timed for crisp throttle response.',
        'Electrical reliability was a priority. The charging system was rebuilt with a new alternator, dual-battery architecture, and improved grounding to eliminate voltage noise and gauge interference. A custom-wired Intellitronix digital cluster provides modern monitoring while maintaining the CJ\'s analog charm.',
        'Cooling, vacuum routing, and accessory systems were simplified and optimized — from a custom sensor layout in the intake manifold to the removal of unnecessary CTO circuits. The result is a clean, functional engine bay where every wire, hose, and fastener serves a purpose.',
        'Built to be driven and worked on, this CJ-5 strikes the balance between classic Jeep authenticity and modern dependability — raw, mechanical, and built by hand from the ground up.'
      ],
      gallery: [
        { src: 'images/placeholders/cj5.JPG', alt: 'Placeholder photo of the Jeep CJ5 exterior stance.' },
        { src: 'images/placeholders/cj52.JPG', alt: 'Placeholder photo showing Jeep CJ5 wiring and plumbing updates.' },
        { src: 'images/placeholders/cj53.JPG', alt: 'Placeholder photo of the Jeep CJ5 body refinements.' },
        { src: 'images/placeholders/cj54.JPG', alt: 'Placeholder photo highlighting the Jeep CJ5 suspension work.' },
        { src: 'images/placeholders/cj55.JPG', alt: 'Placeholder photo focusing on the Jeep CJ5 wiring harness routing.' },
        { src: 'images/placeholders/cj56.JPG', alt: 'Placeholder photo showing the Jeep CJ5 engine bay.' },
        { src: 'images/placeholders/cj57.JPG', alt: 'Placeholder photo of Jeep CJ5 interior updates.' },
        { src: 'images/placeholders/cj58.JPG', alt: 'Placeholder photo documenting Jeep CJ5 trail-ready prep.' },
        { src: 'images/placeholders/cj59.JPG', alt: 'Placeholder photo of the Jeep CJ5 on oversized tires.' },
        { src: 'images/placeholders/cj510.JPG', alt: 'Placeholder photo capturing Jeep CJ5 chassis details.' },
        { src: 'images/placeholders/cj511.JPG', alt: 'Placeholder photo of Jeep CJ5 wiring clean-up.' },
        { src: 'images/placeholders/cj512.JPG', alt: 'Placeholder photo showing Jeep CJ5 paint and trim touches.' },
        { src: 'images/placeholders/cj513.JPG', alt: 'Placeholder photo of the Jeep CJ5 ready for off-road use.' }
      ],
    },
    'cad-butterfly-valve': {
      title: 'Butterfly Valve Assembly',
      category: 'CAD',
      summary: 'Inspect the complete butterfly valve assembly with interchangeable hardware and seals.',
      model: {
        src: 'assets/models/Butterfly_assembly.glb',
        alt: 'Interactive preview of the butterfly valve assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '15deg',
        shadowIntensity: '0.85',
        exposure: '1.05',
        message: 'Place Butterfly_assembly.glb alongside its supporting parts in assets/models to enable the viewer.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/Handle_arm.glb', alt: 'Handle arm component for the butterfly valve assembly', caption: 'Handle arm' },
        { type: 'model', src: 'assets/models/handle_seal_plate.glb', alt: 'Handle seal plate for the butterfly valve assembly', caption: 'Handle seal plate' },
        { type: 'model', src: 'assets/models/M10_nut.glb', alt: 'M10 nut from the butterfly valve assembly', caption: 'M10 nut' },
        { type: 'model', src: 'assets/models/m12Bolt.glb', alt: 'M12 bolt for the butterfly valve assembly', caption: 'M12 bolt' },
        { type: 'model', src: 'assets/models/m12Nut.glb', alt: 'M12 nut for the butterfly valve assembly', caption: 'M12 nut' },
        { type: 'model', src: 'assets/models/m3screw.glb', alt: 'M3 screw for the butterfly valve assembly', caption: 'M3 screw' },
        { type: 'model', src: 'assets/models/panhead_m5.glb', alt: 'Pan head M5 fastener for the butterfly valve assembly', caption: 'Pan head M5 screw' },
        { type: 'model', src: 'assets/models/Pipe.glb', alt: 'Pipe section for the butterfly valve assembly', caption: 'Pipe section' },
        { type: 'model', src: 'assets/models/valve_blade.glb', alt: 'Valve blade component of the butterfly valve', caption: 'Valve blade' },
        { type: 'model', src: 'assets/models/valve_body.glb', alt: 'Valve body for the butterfly valve assembly', caption: 'Valve body' },
        { type: 'model', src: 'assets/models/valve_shaft.glb', alt: 'Valve shaft for the butterfly valve assembly', caption: 'Valve shaft' },
        { type: 'model', src: 'assets/models/Woodruff_key.glb', alt: 'Woodruff key for the butterfly valve assembly', caption: 'Woodruff key' }
      ],
      showGalleryCTA: true,
    },
    'cad-spindle-assembly': {
      title: 'Spindle Assembly',
      category: 'CAD',
      summary: 'Review the full spindle stack-up with its bearings, collar, and base ready for fabrication.',
      model: {
        src: 'assets/models/spindle_assembly.glb',
        alt: 'Interactive preview of the spindle assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '12deg',
        shadowIntensity: '0.85',
        exposure: '1.04',
        message: 'Store spindle_assembly.glb in assets/models with the supporting part exports so the viewer can load every piece.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/spindle_base.glb', alt: 'Spindle base component of the assembly', caption: 'Spindle base' },
        { type: 'model', src: 'assets/models/spindle_bearing.glb', alt: 'Spindle bearing used in the assembly', caption: 'Spindle bearing' },
        { type: 'model', src: 'assets/models/spindle_collar.glb', alt: 'Collar component from the spindle assembly', caption: 'Spindle collar' },
        { type: 'model', src: 'assets/models/spindle_pin.glb', alt: 'Locking pin for the spindle assembly', caption: 'Spindle pin' },
        { type: 'model', src: 'assets/models/spindle_shaft.glb', alt: 'Shaft component for the spindle assembly', caption: 'Spindle shaft' }
      ],
      showGalleryCTA: true,
    },
    'cad-cart-assembly': {
      title: 'Utility Cart Assembly',
      category: 'CAD',
      summary: 'Explore the complete utility cart build with modular casters, bumpers, and removable handle hardware.',
      model: {
        src: 'assets/models/Cart_assembly.glb',
        alt: 'Interactive preview of the utility cart assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '12deg 0deg 0deg',
        shadowIntensity: '0.85',
        exposure: '1.05',
        message: 'Place Cart_assembly.glb and each supporting component listed below in assets/models to enable the gallery viewers.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/Cart_assembly.glb', alt: 'Complete utility cart assembly', caption: 'Cart assembly' },
        { type: 'model', src: 'assets/models/bumper.glb', alt: 'Protective bumper for the utility cart', caption: 'Bumper' },
        { type: 'model', src: 'assets/models/caster_axle_bushing.glb', alt: 'Caster axle bushing for the utility cart', caption: 'Caster axle bushing' },
        { type: 'model', src: 'assets/models/caster_axle_nut.glb', alt: 'Caster axle nut for the utility cart', caption: 'Caster axle nut' },
        { type: 'model', src: 'assets/models/caste_axle.glb', alt: 'Caster axle component for the utility cart', caption: 'Caster axle' },
        { type: 'model', src: 'assets/models/caster_wheel_frame.glb', alt: 'Caster wheel frame for the utility cart', caption: 'Caster wheel frame' },
        { type: 'model', src: 'assets/models/caster_wheel_subassembly.glb', alt: 'Caster wheel subassembly for the utility cart', caption: 'Caster wheel subassembly' },
        { type: 'model', src: 'assets/models/caster_wheel.glb', alt: 'Caster wheel for the utility cart', caption: 'Caster wheel' },
        { type: 'model', src: 'assets/models/frame_subassembly.glb', alt: 'Frame subassembly for the utility cart', caption: 'Frame subassembly' },
        { type: 'model', src: 'assets/models/frame.glb', alt: 'Main frame for the utility cart', caption: 'Frame' },
        { type: 'model', src: 'assets/models/handle_carrier.glb', alt: 'Handle carrier component for the utility cart', caption: 'Handle carrier' },
        { type: 'model', src: 'assets/models/handle_cart.glb', alt: 'Handle for the utility cart', caption: 'Handle' },
        { type: 'model', src: 'assets/models/handle_subassembly.glb', alt: 'Handle subassembly for the utility cart', caption: 'Handle subassembly' },
        { type: 'model', src: 'assets/models/mounting_nut.glb', alt: 'Mounting nut for the utility cart assembly', caption: 'Mounting nut' },
        { type: 'model', src: 'assets/models/platform.glb', alt: 'Platform deck for the utility cart', caption: 'Platform' },
        { type: 'model', src: 'assets/models/swivel_caster_frame.glb', alt: 'Swivel caster frame for the utility cart', caption: 'Swivel caster frame' },
        { type: 'model', src: 'assets/models/swivel_caster_wheel.glb', alt: 'Swivel caster wheel for the utility cart', caption: 'Swivel caster wheel' }
      ],
      showGalleryCTA: true,
    },
    'cad-engine-tla': {
      title: 'TLA Engine Assembly',
      category: 'CAD',
      summary: 'Rotate through the TLA engine concept with piston, crank, and fuel subsystems exported for review.',
      model: {
        src: 'assets/models/Engine_TLA_assembly.glb',
        alt: 'Interactive preview of the complete TLA engine assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '12deg',
        shadowIntensity: '0.88',
        exposure: '1.05',
        message: 'Copy Engine_TLA_assembly.glb and each supporting component listed below into assets/models/ so the viewer can load the full engine.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/Engine_TLA_assembly.glb', alt: 'Full assembly view of the TLA engine', caption: 'Engine assembly' },
        { type: 'model', src: 'assets/models/cam_roller.glb', alt: 'Cam roller component from the TLA engine assembly', caption: 'Cam roller' },
        { type: 'model', src: 'assets/models/connecting_pin.glb', alt: 'Connecting pin for the TLA engine', caption: 'Connecting pin' },
        { type: 'model', src: 'assets/models/connecting_rod.glb', alt: 'Connecting rod for the TLA engine', caption: 'Connecting rod' },
        { type: 'model', src: 'assets/models/crank_bushing.glb', alt: 'Crank bushing used in the TLA engine', caption: 'Crank bushing' },
        { type: 'model', src: 'assets/models/crank_cam_subassembly.glb', alt: 'Crank cam subassembly for the TLA engine', caption: 'Crank cam subassembly' },
        { type: 'model', src: 'assets/models/crank_washer.glb', alt: 'Crank washer component for the TLA engine', caption: 'Crank washer' },
        { type: 'model', src: 'assets/models/crank.glb', alt: 'Crank component for the TLA engine', caption: 'Crank' },
        { type: 'model', src: 'assets/models/crankshaft.glb', alt: 'Crankshaft of the TLA engine', caption: 'Crankshaft' },
        { type: 'model', src: 'assets/models/engine_base.glb', alt: 'Engine base for the TLA assembly', caption: 'Engine base' },
        { type: 'model', src: 'assets/models/engine_body.glb', alt: 'Engine body structure for the TLA assembly', caption: 'Engine body' },
        { type: 'model', src: 'assets/models/engine_cylinder.glb', alt: 'Engine cylinder component for the TLA assembly', caption: 'Engine cylinder' },
        { type: 'model', src: 'assets/models/fuel_container_subassembly.glb', alt: 'Fuel container subassembly for the TLA engine', caption: 'Fuel container subassembly' },
        { type: 'model', src: 'assets/models/Fuel_tank_base.glb', alt: 'Fuel tank base for the TLA engine', caption: 'Fuel tank base' },
        { type: 'model', src: 'assets/models/Fuel_tank_body.glb', alt: 'Fuel tank body for the TLA engine', caption: 'Fuel tank body' },
        { type: 'model', src: 'assets/models/fuel_tank_lid.glb', alt: 'Fuel tank lid for the TLA engine', caption: 'Fuel tank lid' },
        { type: 'model', src: 'assets/models/fuel_tank_spout.glb', alt: 'Fuel tank spout for the TLA engine', caption: 'Fuel tank spout' },
        { type: 'model', src: 'assets/models/fuel_container_subassembly.glb', alt: 'Fuel tank subassembly for the TLA engine', caption: 'Fuel tank subassembly' },
        { type: 'model', src: 'assets/models/piston.glb', alt: 'Piston component for the TLA engine', caption: 'Piston' },
        { type: 'model', src: 'assets/models/push_rod.glb', alt: 'Push rod for the TLA engine', caption: 'Push rod' },
        { type: 'model', src: 'assets/models/roller_bushing.glb', alt: 'Roller bushing used in the TLA engine', caption: 'Roller bushing' },
        { type: 'model', src: 'assets/models/roller_fork.glb', alt: 'Roller fork component for the TLA engine', caption: 'Roller fork' },
        { type: 'model', src: 'assets/models/valve.glb', alt: 'Valve component for the TLA engine', caption: 'Valve' },
        { type: 'model', src: 'assets/models/valve_spring_new.glb', alt: 'Updated valve spring for the TLA engine', caption: 'Valve spring (new)' },
        { type: 'model', src: 'assets/models/Valve_spring.glb', alt: 'Valve spring option for the TLA engine', caption: 'Valve spring' },
        { type: 'model', src: 'assets/models/valve_subassembly.glb', alt: 'Valve subassembly for the TLA engine', caption: 'Valve subassembly' },
        { type: 'model', src: 'assets/models/valve_body.glb', alt: 'Valve body component for the TLA engine', caption: 'Valve body' },
        { type: 'model', src: 'assets/models/wrist_pin.glb', alt: 'Wrist pin component for the TLA engine', caption: 'Wrist pin' }
      ],
      showGalleryCTA: true,
    },
    'cad-1': {
      title: 'Custom Horn Assembly',
      category: 'CAD',
      summary: 'Orbit the in-progress horn assembly concept directly within the carousel.',
      model: {
        src: 'assets/models/horn.glb',
        alt: 'Interactive preview of the custom horn assembly placeholder mesh',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '15deg',
        shadowIntensity: '0.8',
        exposure: '1.1',
        message: 'Keep horn.glb and its exported companions together in assets/models so the viewer can load the CAD preview.'
      },
      showGalleryCTA: true,
    },
    'cad-2': {
      title: 'Precision Bench Vice',
      category: 'CAD',
      summary: 'Explore the multi-part jaw assembly, screw drive, and mounting hardware ready for machining.',
      model: {
        src: 'assets/models/a6_assembly_thanfor_asm.glb',
        alt: 'Interactive preview of the precision bench vice assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '12deg',
        shadowIntensity: '0.9',
        exposure: '1.05',
        message: 'Place a6_assembly_thanfor_asm.glb in assets/models along with each companion component listed in the gallery. Include any separate texture files or .bin companions alongside the GLB if exported as GLTF.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/a6_assembly_thanfor_asm.glb', alt: 'Complete bench vice assembly overview', caption: 'Full assembly' },
        { type: 'model', src: 'assets/models/base.glb', alt: 'Base plate component of the bench vice', caption: 'Base' },
        { type: 'model', src: 'assets/models/jaw_plate.glb', alt: 'Jaw plate detail for the bench vice', caption: 'Jaw plate' },
        { type: 'model', src: 'assets/models/lock_screw.glb', alt: 'Lock screw component of the bench vice', caption: 'Lock screw' },
        { type: 'model', src: 'assets/models/moving_jaw_thanfor_asm.glb', alt: 'Moving jaw subassembly with hardware', caption: 'Moving jaw subassembly' },
        { type: 'model', src: 'assets/models/moving_jaw.glb', alt: 'Moving jaw component of the bench vice', caption: 'Moving jaw' },
        { type: 'model', src: 'assets/models/pin.glb', alt: 'Alignment pin used within the bench vice', caption: 'Pin' },
        { type: 'model', src: 'assets/models/ring.glb', alt: 'Retaining ring component for the bench vice', caption: 'Retaining ring' },
        { type: 'model', src: 'assets/models/screw_collar.glb', alt: 'Screw collar detail of the bench vice', caption: 'Screw collar' },
        { type: 'model', src: 'assets/models/screw_rod.glb', alt: 'Lead screw rod for actuating the bench vice jaws', caption: 'Screw rod' },
        { type: 'model', src: 'assets/models/washer_a.glb', alt: 'Washer A from the bench vice assembly', caption: 'Washer A' },
        { type: 'model', src: 'assets/models/washer_b.glb', alt: 'Washer B from the bench vice assembly', caption: 'Washer B' }
      ],
      showGalleryCTA: true,
    },
    'cad-3': {
      title: 'RC Car Chassis Study',
      category: 'CAD',
      summary: 'View suspension pickup points, battery placement, and aero details for a performance RC platform.',
      model: {
        src: 'assets/models/car_final.glb',
        alt: 'Interactive preview of the finalized RC car assembly',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '14deg',
        shadowIntensity: '0.7',
        exposure: '1.0',
        message: 'Copy car_final.glb into assets/models. If your export references textures, keep them in the same folder for seamless loading.'
      },
      gallery: [
        { type: 'model', src: 'assets/models/bearing608-2rs.glb', alt: '608-2RS wheel bearing used in the RC car assembly', caption: '608-2RS bearing' },
        { type: 'model', src: 'assets/models/breadboard.glb', alt: 'Electronics breadboard layout for the RC car electronics', caption: 'Breadboard layout' },
        { type: 'model', src: 'assets/models/breadboard_platform.glb', alt: 'Mounting platform that supports the electronics breadboard', caption: 'Breadboard platform' },
        { type: 'model', src: 'assets/models/chass_copy_for_hood.glb', alt: 'Chassis hood subassembly for bodywork fitment', caption: 'Chassis hood section' },
        { type: 'model', src: 'assets/models/chassis_v1.glb', alt: 'Initial chassis revision for the RC car concept', caption: 'Chassis v1' },
        { type: 'model', src: 'assets/models/drive_motor.glb', alt: 'Drive motor package for the RC car', caption: 'Drive motor' },
        { type: 'model', src: 'assets/models/esp32s.glb', alt: 'ESP32S controller used for vehicle electronics', caption: 'ESP32S controller' },
        { type: 'model', src: 'assets/models/front_axle.glb', alt: 'Front axle assembly for the RC car', caption: 'Front axle' },
        { type: 'model', src: 'assets/models/front_wheelhub_sub-assembly_fd.glb', alt: 'Front wheel hub sub-assembly with steering knuckle', caption: 'Front wheel hub' },
        { type: 'model', src: 'assets/models/knuckle_fp.glb', alt: 'Front knuckle component for steering geometry', caption: 'Steering knuckle (FP)' },
        { type: 'model', src: 'assets/models/kuckle_fd.glb', alt: 'Rear knuckle variant supporting drivetrain packaging', caption: 'Steering knuckle (FD)' },
        { type: 'model', src: 'assets/models/lipobattery.glb', alt: 'LiPo battery pack model for energy storage', caption: 'LiPo battery' },
        { type: 'model', src: 'assets/models/rim_65mm.glb', alt: '65 mm wheel rim design for the RC car', caption: '65 mm rim' },
        { type: 'model', src: 'assets/models/sg90_hub1.glb', alt: 'SG90 servo horn hub adapter', caption: 'SG90 hub' },
        { type: 'model', src: 'assets/models/tb6612fng.glb', alt: 'TB6612FNG motor driver board', caption: 'TB6612FNG driver' },
        { type: 'model', src: 'assets/models/tie_rod.glb', alt: 'Steering tie rod connecting the knuckles', caption: 'Tie rod' },
        { type: 'model', src: 'assets/models/tire_65mm.glb', alt: '65 mm tire matching the rim design', caption: '65 mm tire' }
      ],
      showGalleryCTA: true,
    },
    'cad-4': {
      title: 'Cow Bell Casting Pattern',
      category: 'CAD',
      summary: 'Inspect the split pattern and draft considerations for a cast aluminum cow bell concept.',
      model: {
        src: 'assets/models/cowbell.glb',
        alt: 'Interactive preview of the cow bell casting pattern',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '10deg',
        shadowIntensity: '0.65',
        exposure: '1.05',
        message: 'Drop cowbell.glb into assets/models. Pair halves, cores, and gating as needed; <model-viewer> reads a single GLB bundle.'
      },
      showGalleryCTA: true,
    },
    'cad-6': {
      title: 'Modular Organizer System',
      category: 'CAD',
      summary: 'Rotate through interchangeable bins and covers tailored for workshop fasteners.',
      model: {
        src: 'assets/models/organizer.glb',
        alt: 'Interactive preview of the modular organizer tray system',
        poster: 'images/placeholders/cad-default.svg',
        autoRotate: true,
        rotationPerSecond: '13deg',
        shadowIntensity: '0.75',
        exposure: '1.04',
        message: 'Save organizer.glb in assets/models. Keep any additional textures beside it so inserts display correctly.'
      },
      showGalleryCTA: true,
    },
    'timer-analysis': {
      title: '555 Timer Emergency Light Circuit & Analysis',
      category: 'Computer & Electrical',
      summary: 'Design, simulate, and validate LMC555 monostable and astable configurations across precise duty cycles.',
      description: [
        'This project explored the design, simulation, and implementation of monostable and astable 555 timer configurations using the LMC555 IC.',
        'Timing constants and RC networks were calculated to dial in 3-second monostable pulses alongside 2-second and 1-second astable oscillators at 60% and 75% duty cycles, respectively, with results confirmed in LTSpice and on the bench.',
        'A dual-timer “police light” flasher further demonstrated waveform generation, reinforcing real-world verification of integrated circuit theory.'
      ],
      report: {
        href: 'assets/reports/555_Timer.pdf',
        label: 'View Full Report'
      },
      gallery: [
        { src: 'assets/reports/LMC555 Internal Circuit Diagram.png', alt: 'Internal block diagram detailing the LMC555 timer architecture.' },
        { src: 'assets/reports/Astable Configuration General Operation Diagram.png', alt: 'General operation diagram explaining the astable 555 timer configuration.' },
        { src: 'assets/reports/Monotstable Configuration General Operation Diagram.png', alt: 'General operation diagram outlining the monostable 555 timer configuration.' },
        { src: 'assets/reports/Spice Circuit Schematic for Astable LMC555.png', alt: 'SPICE schematic for the astable LMC555 circuit used in analysis.' },
        { src: 'assets/reports/Spice Circuit Schematic for Astable LMC555 with 1 Second Time period.png', alt: 'SPICE schematic of the astable LMC555 tuned for a one second period.' },
        { src: 'assets/reports/Spice Circuit Schematic for Monostable LMC555 with 3 Second Time Period.png', alt: 'SPICE schematic of the monostable LMC555 generating a three second pulse.' },
        { src: 'assets/reports/LTSpice Circuit Schematic for Police & Emergency Light Flasher’s.png', alt: 'LTSpice schematic for the dual 555 police light flasher circuit.' },
        { src: 'assets/reports/LTSpice Simulation of Astable LMC555 Circuit 1 sec 75 percent dc.png', alt: 'LTSpice simulation output of the astable LMC555 circuit at 75 percent duty cycle.' },
        { src: 'assets/reports/LTSpice Simulation of Astable LMC555 Circuit |.png', alt: 'Additional LTSpice simulation results for the astable LMC555 circuit.' },
        { src: 'assets/reports/LTSpice Simulation of Monostable LMC555 Circuit With 3 Second Pulse.png', alt: 'LTSpice simulation of the monostable LMC555 delivering a three second pulse.' },
        { src: 'assets/reports/LTSpice Simulation of Police Lights Astable Dual Circuit.png', alt: 'LTSpice simulation showing alternating outputs for the police light flasher.' },
        { src: 'assets/reports/Oscilloscope Measurment of Astable LMC555 Circuit 1 sec 75 percent dc.png', alt: 'Oscilloscope capture of the astable LMC555 circuit with a 1 second period and 75 percent duty cycle.' },
        { src: 'assets/reports/Oscilloscope Measurment of Astable LMC555 Circuit 2 sec 60 percent dc.png', alt: 'Oscilloscope capture of the astable LMC555 circuit at a 2 second period and 60 percent duty cycle.' },
        { src: 'assets/reports/Oscilloscope Measurment of Monostable LMC555 Circuit With 3 Second Pulse.png', alt: 'Oscilloscope capture of the monostable LMC555 circuit producing a three second pulse.' },
        { src: 'assets/reports/Oscilloscope Measurment of Police Lights Astable Dual Circuit.png', alt: 'Oscilloscope capture of the alternating police light dual astable circuit.' },
        { src: 'assets/reports/Police Lights LED Flasher Circuit Diagram from Elonics. Org.png', alt: 'Reference LED flasher circuit diagram from Elonics.org used for comparison.' }
      ],
    },
    'audio-eq': {
      title: '3-Band Audio Equalizer and Power Amplifier',
      category: 'Computer & Electrical',
      summary: 'Shape bass, mids, and treble with LM324 filters before delivering over 400 mW through an LM386 output stage.',
      description: [
        'This project designed and built a fully functional 3-band audio equalizer and power amplifier capable of driving an 8Ω speaker.',
        'Low-, band-, and high-pass filters isolate frequency ranges with LM324 op-amps providing individual gain control, while a master volume feeds an LM386 power amplifier for clean output.',
        'Frequency response sweeps and RMS power measurements verified the -3 dB targets and showcased the system’s adjustable tone balancing.'
      ],
      report: {
        href: 'assets/reports/Final_Report.pdf',
        label: 'View Full Report'
      },
      gallery: [
        { src: 'assets/reports/320mV_input_maxVolume.png', alt: 'Oscilloscope capture showing the equalizer handling a 320 mV input at maximum volume.' },
        { src: 'assets/reports/320mV_input_Mid_Volume.png', alt: 'Oscilloscope capture of the 320 mV input at mid volume output level.' },
        { src: 'assets/reports/320mV_input_Min_Volume.png', alt: 'Oscilloscope capture of the 320 mV input running through the equalizer at minimum volume.' },
        { src: 'assets/reports/AC_RMS_output_MidVolume.png', alt: 'True RMS AC output measurement while the equalizer operates at mid volume.' },
        { src: 'assets/reports/amp_output_schematic.png', alt: 'Amplifier output schematic detailing the LM386 stage.' },
        { src: 'assets/reports/BPF_frequencyResponseAnalysis.png', alt: 'Band-pass filter frequency response analysis plot.' },
        { src: 'assets/reports/BPF_schematic.png', alt: 'Band-pass filter schematic used in the equalizer.' },
        { src: 'assets/reports/equalizer_schematic.png', alt: 'Overall schematic of the three-band equalizer signal chain.' },
        { src: 'assets/reports/gain_adjustment_schematic.png', alt: 'Gain adjustment circuit schematic for the equalizer filters.' },
        { src: 'assets/reports/HPF_frequencyResponseAnalysis.png', alt: 'High-pass filter frequency response analysis plot.' },
        { src: 'assets/reports/HPF_schematic.png', alt: 'High-pass filter schematic showing component values.' },
        { src: 'assets/reports/LPF_frequencyResponseAnalysis.png', alt: 'Low-pass filter frequency response analysis plot.' },
        { src: 'assets/reports/LPF_schematic.png', alt: 'Low-pass filter schematic with component references.' },
        { src: 'assets/reports/LF356_pinout.png', alt: 'LF356 op-amp pinout reference used during design.' },
        { src: 'assets/reports/LM324_pinout.png', alt: 'LM324 pinout diagram supporting the filter stages.' },
        { src: 'assets/reports/LM386_pinout.png', alt: 'LM386 power amplifier pinout reference.' },
        { src: 'assets/reports/LM386_schematic.png', alt: 'LM386 amplifier schematic for the power stage.' },
        { src: 'assets/reports/Max_gain_AC_Output_100Hz.png', alt: 'Maximum gain AC output measurement at 100 Hz.' },
        { src: 'assets/reports/Max_gain_AC_Output_1000Hz.png', alt: 'Maximum gain AC output measurement at 1 kHz.' },
        { src: 'assets/reports/Max_gain_AC_Output_10000Hz.png', alt: 'Maximum gain AC output measurement at 10 kHz.' },
        { src: 'assets/reports/Min_gain_AC_Output_100Hz.png', alt: 'Minimum gain AC output measurement at 100 Hz.' },
        { src: 'assets/reports/Min_gain_AC_Output_1000Hz.png', alt: 'Minimum gain AC output measurement at 1 kHz.' },
        { src: 'assets/reports/Min_gain_AC_Output_10000Hz.png', alt: 'Minimum gain AC output measurement at 10 kHz.' },
        { src: 'assets/reports/Signal_RMS_100Hz.png', alt: 'Signal RMS measurement taken at 100 Hz.' },
        { src: 'assets/reports/Signal_RMS_768Hz.png', alt: 'Signal RMS measurement taken at 768 Hz.' },
        { src: 'assets/reports/Signal_summer_schematic.png', alt: 'Signal summer schematic combining the three bands.' }
      ],
    },
    'portfolio-site': {
      title: 'Portfolio Website Experience',
      category: 'Computer & Electrical',
      summary: 'Custom-built site to present projects efficiently with immersive galleries and interactive viewers.',
      description: [
        'I designed and built this responsive portfolio from the ground up so my engineering and fabrication work is easy to explore at a glance.',
        'A combination of HTML, CSS, and Javascript drive  and  the modals, galleries, and 3D viewers, ensuring every project can be showcased in its intended format.',
        'Accessibility, depth, and a cohesive visual experience were priorities so prospective collaborators can quickly absorb the scope of my abilities.'
      ],
      gallery: [
        {
          type: 'live',
          src: 'index.html?viewport=desktop',
          title: 'Interactive homepage preview',
          sandbox: 'allow-scripts allow-same-origin',
          badge: 'Live preview',
          message: 'Interact with the responsive homepage hero exactly like the mini viewer.',
        },
        { src: 'images/portfolio-home.png', alt: 'Homepage of the Tristan Hanford portfolio website featuring the hero section and project highlights.', caption: 'Homepage hero introducing the portfolio experience.' }
      ],
      showGalleryCTA: false,
    },
    'smart-mirror': {
      title: 'Alexa Integrated Smart Mirror',
      category: 'Computer & Electrical',
      summary: 'Voice-enabled display with embedded LEDs, microphone array, and responsive UI.',
      gallery: [
        { src: 'images/placeholders/coming-soon.svg', alt: 'Animated "Coming Soon" card placeholder for the smart mirror front panel.' },
        { src: 'images/placeholders/coming-soon.svg', alt: 'Animated "Coming Soon" card placeholder representing the electronics tray behind the mirror.' }
      ],
    },
    'led-eq': {
      title: 'Sound Reactive LED Equalizer',
      category: 'Computer & Electrical',
      summary: 'FFT-driven light bar that maps audio frequencies to cascading color bands.',
      gallery: [
        { src: 'images/placeholders/coming-soon.svg', alt: 'Animated "Coming Soon" card placeholder for the sound reactive LED equalizer in action.' },
        { src: 'images/placeholders/coming-soon.svg', alt: 'Animated "Coming Soon" card placeholder showing the controller enclosure for the LED equalizer.' }
      ],
    }
  };

  window.ProjectData = Object.freeze(data);
})();
